on:
  workflow_dispatch: # allows manual trigger

name: Update Latest Template Tags

jobs:
  update-tag:
    name: Update the latest tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Update latest tag
        run: 'TAG=$(git describe --abbrev=0 --tags --match "releases/templates/*") && git tag -f releases/templates/latest "$TAG"'

      - name: Push Tag
        run: git push origin releases/templates/latest --force
