on:
  workflow_dispatch: # allows manual trigger

name: Update Latest Template Tags

jobs:
  update-tag:
    name: Update the latest tag
    runs-on: ubuntu-latest
    #permissions:
    #  actions: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      #- name: Update latest tag
      #  run: 'TAG=$(git describe --abbrev=0 --tags --match "releases/templates/v*") && git tag -f releases/templates/latest "$TAG"'

      - name: Update latest tag
        run: 'export TAG=$(git describe --abbrev=0 --tags --match "releases/templates/v*")'

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "latest"
          commit_sha: ${{ env.TAG }}
          force_push_tag: true
          message: "Latest Release"

      #- name: Push Tag
      #  run: git push origin releases/templates/latest
